# tinygrad relies on metal support in macOS 14+
# io_uring needs newer glibc
c_stdlib_version:   # [unix]
  - 2.28            # [linux]
  - 2.28            # [linux]
  - 15.5            # [osx]
MACOSX_SDK_VERSION: # [osx]
  - 15.5            # [osx]
