# tinygrad relies on metal support
c_stdlib_version:   # [osx]
  - 15.5            # [osx]
MACOSX_SDK_VERSION: # [osx]
  - 15.5            # [osx]

github_actions_labels:  # [osx]
- cirun-macos-m4-large  # [osx]
