# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on:
  push:

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include:
          - CONFIG: linux_64_cuda_compiler_version12.9github_actions_labelscirun-openstack-gpu-2xlargepython3.11.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9github_h683f767a', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_64_cuda_compiler_version12.9github_actions_labelscirun-openstack-gpu-2xlargepython3.12.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9github_hed05c094', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_64_cuda_compiler_version12.9github_actions_labelscirun-openstack-gpu-2xlargepython3.13.____cp313
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9github_h0d460f21', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_64_cuda_compiler_version12.9github_actions_labelscirun-openstack-gpu-2xlargepython3.14.____cp314
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version12.9github_h020cead9', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_64_cuda_compiler_version13.0github_actions_labelscirun-openstack-gpu-2xlargepython3.11.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version13.0github_ha9c198a9', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_64_cuda_compiler_version13.0github_actions_labelscirun-openstack-gpu-2xlargepython3.12.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version13.0github_hf84370a9', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_64_cuda_compiler_version13.0github_actions_labelscirun-openstack-gpu-2xlargepython3.13.____cp313
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version13.0github_h39cc603f', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_64_cuda_compiler_version13.0github_actions_labelscirun-openstack-gpu-2xlargepython3.14.____cp314
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_64_cuda_compiler_version13.0github_h7a79311c', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_64_cuda_compiler_versionNonegithub_actions_labelscirun-openstack-cpu-largepython3.11.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_cuda_compiler_versionNonegithub_h881b1748', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonegithub_actions_labelscirun-openstack-cpu-largepython3.12.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_cuda_compiler_versionNonegithub_ha43e1be3', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonegithub_actions_labelscirun-openstack-cpu-largepython3.13.____cp313
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_cuda_compiler_versionNonegithub_h942c4016', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_64_cuda_compiler_versionNonegithub_actions_labelscirun-openstack-cpu-largepython3.14.____cp314
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_64_cuda_compiler_versionNonegithub_hde9807f8', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_version12.9github_actions_labelscirun-openstack-gpu-2xlargepython3.11.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_version12.9g_hf014a623', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_aarch64_cuda_compiler_version12.9github_actions_labelscirun-openstack-gpu-2xlargepython3.12.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_version12.9g_h690bad88', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_aarch64_cuda_compiler_version12.9github_actions_labelscirun-openstack-gpu-2xlargepython3.13.____cp313
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_version12.9g_h9da23deb', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_aarch64_cuda_compiler_version12.9github_actions_labelscirun-openstack-gpu-2xlargepython3.14.____cp314
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_version12.9g_h6b0a980b', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_aarch64_cuda_compiler_version13.0github_actions_labelscirun-openstack-gpu-2xlargepython3.11.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_version13.0g_h73f12294', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_aarch64_cuda_compiler_version13.0github_actions_labelscirun-openstack-gpu-2xlargepython3.12.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_version13.0g_he47e2367', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_aarch64_cuda_compiler_version13.0github_actions_labelscirun-openstack-gpu-2xlargepython3.13.____cp313
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_version13.0g_h79f8e77f', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_aarch64_cuda_compiler_version13.0github_actions_labelscirun-openstack-gpu-2xlargepython3.14.____cp314
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-gpu-2xlarge--${{ github.run_id }}-linux_aarch64_cuda_compiler_version13.0g_hb57970e2', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
            CONDA_FORGE_DOCKER_RUN_ARGS: "--gpus all"
          - CONFIG: linux_aarch64_cuda_compiler_versionNonegithub_actions_labelscirun-openstack-cpu-largepython3.11.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNoneg_h1bccb1a1', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonegithub_actions_labelscirun-openstack-cpu-largepython3.12.____cpython
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNoneg_h193e1914', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonegithub_actions_labelscirun-openstack-cpu-largepython3.13.____cp313
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNoneg_hf72cd245', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: linux_aarch64_cuda_compiler_versionNonegithub_actions_labelscirun-openstack-cpu-largepython3.14.____cp314
            UPLOAD_PACKAGES: True
            os: ubuntu
            runs_on: ['cirun-openstack-cpu-large--${{ github.run_id }}-linux_aarch64_cuda_compiler_versionNoneg_h205d29fc', 'linux', 'x64', 'self-hosted']
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
          - CONFIG: osx_arm64_python3.11.____cpython
            UPLOAD_PACKAGES: True
            os: macos
            runs_on: ['cirun-macos-m4-large--${{ github.run_id }}-osx_arm64_python3.11.____cpython', 'macOS', 'arm64', 'self-hosted']
          - CONFIG: osx_arm64_python3.12.____cpython
            UPLOAD_PACKAGES: True
            os: macos
            runs_on: ['cirun-macos-m4-large--${{ github.run_id }}-osx_arm64_python3.12.____cpython', 'macOS', 'arm64', 'self-hosted']
          - CONFIG: osx_arm64_python3.13.____cp313
            UPLOAD_PACKAGES: True
            os: macos
            runs_on: ['cirun-macos-m4-large--${{ github.run_id }}-osx_arm64_python3.13.____cp313', 'macOS', 'arm64', 'self-hosted']
          - CONFIG: osx_arm64_python3.14.____cp314
            UPLOAD_PACKAGES: True
            os: macos
            runs_on: ['cirun-macos-m4-large--${{ github.run_id }}-osx_arm64_python3.14.____cp314', 'macOS', 'arm64', 'self-hosted']
    steps:

    - name: Checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Build on Linux
      id: build-linux
      if: matrix.os == 'ubuntu'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        CI: github_actions
        CONDA_FORGE_DOCKER_RUN_ARGS: "${{ matrix.CONDA_FORGE_DOCKER_RUN_ARGS }}"
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        if [[ "$(uname -m)" == "x86_64" ]]; then
          echo "::group::Configure binfmt_misc"
          docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        fi
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        echo "::endgroup::"
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      id: build-macos
      if: matrix.os == 'macos'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        CI: github_actions
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}
      shell: bash
      run: |
        export flow_run_id="github_$GITHUB_RUN_ID"
        export remote_url="https://github.com/$GITHUB_REPOSITORY"
        export sha="$GITHUB_SHA"
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_osx_build.sh

    - name: Build on windows
      id: build-windows
      if: matrix.os == 'windows'
      shell: cmd
      run: |
        set "flow_run_id=github_%GITHUB_RUN_ID%"
        set "remote_url=https://github.com/%GITHUB_REPOSITORY%"
        set "sha=%GITHUB_SHA%"
        call ".scripts\run_win_build.bat"
      env:
        # default value; make it explicit, as it needs to match with artefact
        # generation below. Not configurable for now, can be revisited later
        CONDA_BLD_DIR: C:\bld
        MINIFORGE_HOME: D:\Miniforge
        PYTHONUNBUFFERED: 1
        CONFIG: ${{ matrix.CONFIG }}
        CI: github_actions
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
        FEEDSTOCK_TOKEN: ${{ secrets.FEEDSTOCK_TOKEN }}
        STAGING_BINSTAR_TOKEN: ${{ secrets.STAGING_BINSTAR_TOKEN }}